sphinx_copybutton/__init__.py
The warning is:
```
extension 'sphinx_copybutton' has no setup() function;
is it really a Sphinx extension module?
```
which comes from:
https://github.com/sphinx-doc/sphinx/blob/4165c8dd62433ac70227f607bb77a36c281b4ed9/sphinx/registry.py#L478-L479
=> Implement a setup() function to avoid a warning.

.circleci/config.yml, README.md, doc/index.rst, doc/requirements.txt, doc/second/second_page.rst, sphinx_copybutton/_static/copybutton.css, sphinx_copybutton/_static/copybutton.js
closes #8 
The only way I could figure how to get the SVG to load properly was to use the github CDN, since otherwise I'm not sure how to determine the relative path to the site root (since it may be a part of a subdirectory on a site)
=> updating svg path, docs, and circleci

doc/conf.py, sphinx_copybutton/_static/copybutton.js
I believe this class is what messed up the viz in the sphinx_read_the_docs theme.
I think it closes #11
=> removing .btn class

sphinx_copybutton/_static/copybutton.css
With the current CSS, the button is aligned at the very top and right of code blocks. That way, it covers the border of code blocks in some of the builtin themes.
See e.g. https://matplotlib.org/devdocs/gallery/images_contours_and_fields/contourf_demo.html or http://pangeo.io/setup_guides/hpc.html
While you cannot make it right for every possible theme, the defaults should play nicely with the builtin sphinx themes.
This PR slightly offsets the button.
Before:
After:
=> Slighly offset the button from top and right

setup.cfg, setup.py
Use the license_file option in setup.cfg to tell setuptools where to find the license.
Remove the include_package_data option which seems to prevent package_data being used (include_package_data needs the data files to be specified in MANIFEST.in).
Fixes #40.
=> Include LICENSE and _static data in generated tarball.

sphinx_copybutton/_static/copybutton.css
This is an attempt to make the appearance of the button more similar between themes.
This is an example with the "alabaster" theme: https://3-229129726-gh.circle-artifacts.com/0/html/index.html
And this is how it looks with the "readthedocs" theme: https://2-229129726-gh.circle-artifacts.com/0/html/index.html
And, for comparison, this is how it would look with the "readthedocs" theme *before* this PR: https://4-229129726-gh.circle-artifacts.com/0/html/index.html
=> CSS: Remove padding from copybtn

MANIFEST.in
When running `python setup.py sdist`, the resulting tarball has the doc/ folder in it.
=> Use MANIFEST.in to include doc/ directory in source archive.

sphinx_copybutton/_static/copybutton.css
This has two changes:
1. There's a .5 second delay on the tooltip hover
2. The tooltip is slightly offset to the left
closes #46
=> minor css tweaks for delay

.circleci/config.yml, .gitmodules, RELEASES.md, setup.py, sphinx_copybutton/__init__.py, sphinx_copybutton/_static/clipboard.min.js
See #43.
This is the resulting HTML: https://11-229129726-gh.circle-artifacts.com/0/html/index.html
Since this did not cause an error message when the submodule was not checked out, I have added an error message in cbadffe890790762b806e566039aa32a4d6d9552.
This should work both from the Git repo and from an `sdist`.
I do *not* know, however, whether this works as intended on a platform that doesn't support symbolic links.
This is not a problem when *using* the `wheel` or `sdist`, but it *might* be a problem when *creating* the package on a system without symlink support.
=> Add clipboard.js as git submodule

doc/index.rst, sphinx_copybutton/__init__.py, sphinx_copybutton/_static/copybutton.js
This adds the ability to **not copy** certain chunks of text from code cells. It's meant for when there are prompts included with a code cell that you don't want copied (e.g., `>>> `). It modifies the javascript callback so that it:
1. Grabs the target code cell text
2. Checks each line to see if it begins with the user-configured "skip" text
3. If so, removes that text from the beginning of each line before copying
closes #30
=> adding text replace feature

sphinx_copybutton/__init__.py
This has already been done for `add_javascript()` -> `add_js_file()`, so there should be no change in compatible versions.
=> Avoid a Sphinx warning: add_stylesheet -> add_css_file

.gitignore, sphinx_copybutton/_static/copybutton.css, sphinx_copybutton/_static/copybutton.js
This fixes some issues with some specific themes ([see](https://github.com/spatialaudio/nbsphinx/issues/376)).
Some problems are a result of css rules being overwritten by theme rules (astropy-theme, py3doc-enhanced-theme, typlog-theme), others are a result of an old way (julia-theme, pytorch-theme, itcase-theme, pyviz-theme) to include additional javascript files in a theme.
The old way to include javascript files (`<script type="text/javascript" src="{{ pathto(scriptfile, 1) }}"></script>`) does not support a [missing file name](https://github.com/choldgraf/sphinx-copybutton/blob/7ab883110a02caa88dc025052f1154cae03af2fa/sphinx_copybutton/__init__.py#L12) so the browser tries to fetch a file `None`, which leaves `copybuttonSkipText` as undefined and breaks the copy functionality. If a …
=> Fix problems with some themes

sphinx_copybutton/_static/copybutton.js_t
To avoid copying styles and scripts, this makes it work with the sphinx-prompt extension.
https://www.w3schools.com/jsref/prop_node_innertext.asp
I hacked it like this in my conf.py file for now:
```
copybutton_prompt_text = """>>> ';
textContent = target.innerText.split('\\n'); var dummy = '
"""
```
=> Use innerText instead of textContent

sphinx_copybutton/_static/copybutton.css
When you do *not* use the copy button to copy text, but you select text in the old-fashioned way to copy it, you might also inadvertently select the button itself. This especially happens when selecting multiple adjacent code blocks.
This is a minor aesthetic glitch, but the real problem is that the `alt` text (typically "Copy to clipboard") ends up polluting the clipboard!
=> Make button un-selectable

doc/conf.py, doc/index.rst, sphinx_copybutton/_static/copybutton.js_t, sphinx_copybutton/_static/test.js
As concluded in #86, this fixes the way that `copybutton_prompt_text` is injected into `copybutton.js_t`.
And updates the docs on how to use the regex feature.
I left the old tests in there, since I kind like those oddities if you know them. But if that is too much clutter for you I can remove them.
Not sure how much you value [SemVer](https://semver.org/) but this is a breaking change, since it will break functionality for people that already use the regex feature. 
fixes #86 
**Note**: I left #84 ([besides](https://github.com/executablebooks/sphinx-copybutton/issues/84#issuecomment-645670875)) untouched, since IMHO this should configurable i.e. by a variable `copy_blank_lines`.  I just can see someone complaining around the corner, even so 'copy as is' is the most natural thing and …
=> Fix regex escaping

README.md, doc/index.rst
Since `sphinx-copybutton` [is also available via conda-forge](https://anaconda.org/conda-forge/sphinx-copybutton), it should be mentioned in the docs. And as a bonus this adds a pretty badge 😋
=> 📖 DOC: Add conda-forge badge and install instructions

doc/conf.py, doc/index.rst
Just a little follow up to #88, adding the regex for line continuation of the python default repl (`r"\.\.\. "`) to the docs.
=> 👌 IMPROVE: Add default python repl continuation regex

sphinx_copybutton/_static/copy-button.svg
Switch to a more minimal icon from Tabler icons!
100% up for discussion, but I reckon this will look nicer for us. It should also some #69 since the icon includes a height and width as well.
=> ✨ IMPROVE: Update copy-button.svg

sphinx_copybutton/_static/copybutton.css
before:
after: 
This became apparent due to the new button image #98. For the old button image, the CSS worked by chance (`a.copybutton.width = 1em` is as wide as the old image was.).
=> 🐛 FIX: Fix button position

setup.py
- This change is obvious from the diff.
- GitHub organization has changed, update setup.py
=> 🔧 MAINT: Fix GitHub link to new organization name

.pre-commit-config.yaml, setup.py
The CI is failing, for [example](https://github.com/executablebooks/sphinx-copybutton/pull/122/checks?check_run_id=2558493872):
> Error:  The hook `black` requires pre-commit version 2.9.2 but version 1.17.0 is installed.  Perhaps run `pip install --upgrade pre-commit`.
The first commit here updates the pre-commit pin to the latest 2.12.1. (Perhaps even unpin this?)
---
Next, when running pre-commit, it warns:
> [WARNING] The 'rev' field of repo 'https://github.com/psf/black' appears to be a mutable reference (moving tag / branch).  Mutable references are never updated after first install and are not supported.  See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details.  Hint: `pre-commit autoupdate` often fixes this.
The second commit runs `pre-commit …
=> 🔧 MAINT: fix pre-commit

.gitignore, doc/index.rst, sphinx_copybutton/__init__.py, sphinx_copybutton/_static/copybutton.js_t, sphinx_copybutton/_static/copybutton_funcs.js, sphinx_copybutton/_static/test.js
Dear Chris,
this is an attempt to resolve #84 reported by @chrisjsewell. Let me know what you think about it.
With kind regards,
Andreas.
---
Edit: As per discussion at https://github.com/executablebooks/sphinx-copybutton/pull/127#issuecomment-850317061 ff., this patch, now, both:
- brings in the baseline feature (f18bd05)
- _and_ makes "copying empty lines" the default behavior (da08b04).
=> 👌 IMPROVE: Allow copying empty lines

.github/workflows/integration.yml, doc/conf.py, doc/index.rst, setup.py
* Update docs to reflect 3.6+ is supported
* Test CI with Python 3.9 and bump actions versions
* Add `python_requires` to help pip install the right version for the user
* Add Trove classifier metadata for the Python versions for display on PyPI
* Upgrade Python syntax with https://github.com/asottile/pyupgrade (this also has a pre-commit hook available)
=> 🔧 MAINT: Update Python versions in metadata and tests

doc/conf.py, doc/index.rst, package-lock.json, package.json, sphinx_copybutton/__init__.py, sphinx_copybutton/_static/copybutton.js_t, sphinx_copybutton/_static/copybutton_funcs.js, sphinx_copybutton/_static/test.js
potentially ...
closes #111
closes #119
closes #122
closes #124
if d050f87 is not reverted, see https://github.com/executablebooks/sphinx-copybutton/pull/126#pullrequestreview-680436724 for more context.
------
closes #105 
This PR is the execution of what I described in https://github.com/executablebooks/sphinx-copybutton/issues/105#issuecomment-848843006.
It allows copying blocks like:
```
$ datalad download-url http://www.tldp.org/LDP/Bash-Beginners-Guide/Bash-Beginners-Guide.pdf \
--dataset . \
-m "add beginners guide on bash" \
-O books/bash_guide.pdf
```
and 
```
$ cat << EOT > notes.txt
One can create a new dataset with 'datalad create [--description] PATH'.
The dataset is created empty
EOT
```
I am aware that my solution is perhaps not very robust and/or beautiful. I am opening …
=> ✨ NEW: Add line continuation matching and "HERE-documents"

sphinx_copybutton/_static/copybutton.js_t
When building on Read the Docs, the parameter
DOCUMENTATION_OPTIONS.URL_ROOT can return '#' and that returns an
incorrect path to the svg icon for the copy button.
Closes: #121
=> 🐛 FIX: Fix edge-case when page is '#'

docs/conf.py, setup.py, sphinx_copybutton/_static/check-solid.svg, sphinx_copybutton/_static/copy-button.svg, sphinx_copybutton/_static/copybutton.css, sphinx_copybutton/_static/copybutton.js_t, tox.ini
This is an update to the SVG icon + hovering behavior that we use. Now that GitHub has its own copy button auto-added, we might be able to reduce cognitive load on users by mimicking their UX. This PR is an attempt at that!
It also adds in a background color (neutral gray) rather than trying to inherit the background from its parent element, which I think was introducing some variability.
Curious what @pradyunsg thinks 
GitHub behavior:
This PR behavior:
It is hard to get the behavior totally consistent across themes etc, and I had a hard time getting the heights to quite line up, so please make suggestions if you think there are improvements to make there (or elsewhere).
=> ✨ ENH: Update icon to use GitHub style

docs/_static/clipboard.svg, docs/conf.py, docs/index.rst, sphinx_copybutton/_static/copy-button.svg
This updates our icon to use the "copy" copybutton from tabular. It's more in-line with how GitHub styles copy buttons, which is the major inspiration for the design here as well.
I also vaguely remember @pradyunsg saying he thought this was a better design 😅
closes #151
=> ENH: Update copybutton image to match GitHub

.github/workflows/integration.yml, setup.py
Also bump GitHub Actions versions.
We should also [test on Python 3.11 beta](https://discuss.python.org/t/the-last-3-11-beta-release-3-11-0b5-is-now-available/17693) but need to wait for dependency greenlet to support it first:
* https://github.com/python-greenlet/greenlet/issues/305
=> MAINT: Add support for Python 3.10

sphinx_copybutton/_static/copybutton.css, sphinx_copybutton/_static/copybutton.js_t
This makes the copybutton remain on the screen when the `.success` class is still present. It also staggers the timout of when `success` is removed to be *before* the icon changes back, so that we don't get an ugly "icon change back before it hides" effect.
closes #175
=> FIX: Make copybutton remain for a second during success

.github/workflows/integration.yml, .github/workflows/publish.yml, CHANGELOG.md, sphinx_copybutton/__init__.py
Cutting a release to bring in the recent improvements that @rkdarst made.
I've also moved our `Publish to PyPI` action to a dedicated workflow, so that it no longer shows up as a `didn't run` job in our CI/CD and will reduce the noise in merging PRs.
=> RLS: v0.5.1 and move `Publish to PyPI` action to dedicated file

setup.py
Add the Sphinx Extension PyPi classifier so that the extension shows up in the correct [PyPi filters](https://pypi.org/search/?c=Framework+%3A%3A+Sphinx+%3A%3A+Extension).
=> MAINT: Add Sphinx Extension classifier

sphinx_copybutton/__init__.py
- Immediate fix to backwards compatibility of #185.
- I'm not implying I wouldn't want to change the default later.
=> BUG: Don't exclude `.gp` class by default

.github/workflows/integration.yml
Python 3.7 and 3.8 tests aren't working since ubuntu-latest is now using 24.04 (see https://github.com/actions/runner-images/issues/10893). They are also past end-of-life. This PR drops them and adds 3.11-3.13. It also bumps the python-setup to the latest version.
=> ci: update python versions to test
